enum Code {
  SUCCESS = 'SUCCESS',
  NOT_FOUND = 'NOT_FOUND',
  COULD_NOT_BLOCK = 'NOT_FOUND',
  ER_COULD_NOT_DEACTIVATE = 'ER_COULD_NOT_DEACTIVATE',
  ER_COULD_NOT_CHANGE_STATE = 'ER_COULD_NOT_CHANGE_STATE',
  ER_COULD_NOT_ACTIVATE = 'ER_COULD_NOT_ACTIVATE',
  ER_LOGIN = 'ER_LOGIN',
  ER_EMAIL_EXISTS = 'ER_EMAIL_EXISTS',
  ER_EMAIL_FORMAT = 'ER_EMAIL_FORMAT',
  ER_LOGOUT = 'ER_LOGOUT',
}
export default Code
